// SPDX-License-Identifier: GPL-3.0-or-later
// GENERATED by tools/i18n/gen_i18n.py from common/i18n/*.json — DO NOT EDIT BY HAND.
#include "core/Strings.h"

#include <array>
#include <atomic>
#include <cstddef>

namespace rabbitears {
namespace i18n {
namespace {

constexpr std::size_t N = static_cast<std::size_t>(StringId::Count);

// English
constexpr std::array<const char*, N> kEn = {{
    // --- Menu ---
    "Play",  // LabelPlay
    "Play in PIP",  // MenuChannelPlayInPip
    "Show in TV Guide",  // MenuChannelShowInGuide
    "Fullscreen",  // Fullscreen
    "Video only",  // MenuVideoOnlyPlain
    "Single view",  // MenuSingleView
    "Split view (2×2)",  // MenuSplitView
    "MPEG-TS  (.ts)",  // MenuFormatMpegTs
    "Matroska  (.mkv)",  // MenuFormatMatroska
    "MP4  (.mp4)",  // MenuFormatMp4
    "Open File…",  // MenuOpenFile
    "Recording format",  // MenuRecordingFormat
    "Hide unavailable channels",  // MenuHideUnavailable
    "Categories…",  // MenuCategories
    "Export favourites…",  // MenuExportFavourites
    "Import favourites…",  // MenuImportFavourites
    "Refresh Guide…",  // MenuRefreshGuide
    "Scheduled Recordings…",  // MenuScheduledRecordings
    "Recording Rules…",  // MenuRecordingRules
    "Wake this PC to record",  // MenuWakeToRecord
    "Run wake task now",  // MenuRunWakeTaskNow
    "Meters…",  // MenuMeters
    "Video only\\tCtrl+Shift+V",  // MenuVideoOnly
    "Resume last channel",  // MenuResumeLastChannel
    "Single",  // MenuViewSingle
    "Split (2×2)",  // MenuViewSplit
    "Picture-in-picture",  // MenuPictureInPicture
    "View",  // MenuView
    "Reset to default",  // MenuLayoutResetDefault
    "Move sidebar",  // MenuMoveSidebar
    "Move video",  // MenuMoveVideo
    "Move channels",  // MenuMoveChannels
    "To left",  // MenuDockToLeft
    "To right",  // MenuDockToRight
    "To top",  // MenuDockToTop
    "To bottom",  // MenuDockToBottom
    "Save layout as…",  // MenuSaveLayoutAs
    "Apply saved layout",  // MenuApplySavedLayout
    "Delete saved layout",  // MenuDeleteSavedLayout
    "Layout",  // MenuLayout
    "Follow System",  // MenuThemeFollowSystem
    "Theme",  // MenuTheme
    "About…",  // MenuAbout
    "Language",  // MenuLanguage
    "System default",  // LangSystemDefault
    "English",  // LangEnglish
    "日本語",  // LangJapanese
    "Channels",  // MenuChannels
    "Recording",  // MenuRecording
    "Restart to change the display language",  // LangRestartInstruction
    "RabbitEars needs to restart to apply the new language.",  // LangRestartBody
    "Restart now",  // LangRestartNow
    "Later",  // LangRestartLater
    // --- Nav ---
    "Set Guide URL…",  // MenuSetGuideUrl
    "Set Guide URL… (no playlists)",  // MenuGuideSetUrlNoPlaylists
    "United States",  // CountryUnitedStates
    "United Kingdom",  // CountryUnitedKingdom
    "Canada",  // CountryCanada
    "Australia",  // CountryAustralia
    "New Zealand",  // CountryNewZealand
    "Ireland",  // CountryIreland
    "Germany",  // CountryGermany
    "France",  // CountryFrance
    "Spain",  // CountrySpain
    "Italy",  // CountryItaly
    "Portugal",  // CountryPortugal
    "Netherlands",  // CountryNetherlands
    "Belgium",  // CountryBelgium
    "Switzerland",  // CountrySwitzerland
    "Austria",  // CountryAustria
    "Sweden",  // CountrySweden
    "Norway",  // CountryNorway
    "Denmark",  // CountryDenmark
    "Finland",  // CountryFinland
    "Poland",  // CountryPoland
    "Czechia",  // CountryCzechia
    "Slovakia",  // CountrySlovakia
    "Hungary",  // CountryHungary
    "Romania",  // CountryRomania
    "Bulgaria",  // CountryBulgaria
    "Greece",  // CountryGreece
    "Turkey",  // CountryTurkey
    "Russia",  // CountryRussia
    "Ukraine",  // CountryUkraine
    "Serbia",  // CountrySerbia
    "Croatia",  // CountryCroatia
    "Slovenia",  // CountrySlovenia
    "Albania",  // CountryAlbania
    "Brazil",  // CountryBrazil
    "Mexico",  // CountryMexico
    "Argentina",  // CountryArgentina
    "Chile",  // CountryChile
    "Colombia",  // CountryColombia
    "Peru",  // CountryPeru
    "Venezuela",  // CountryVenezuela
    "India",  // CountryIndia
    "Pakistan",  // CountryPakistan
    "Bangladesh",  // CountryBangladesh
    "China",  // CountryChina
    "Japan",  // CountryJapan
    "South Korea",  // CountrySouthKorea
    "Indonesia",  // CountryIndonesia
    "Malaysia",  // CountryMalaysia
    "Singapore",  // CountrySingapore
    "Thailand",  // CountryThailand
    "Vietnam",  // CountryVietnam
    "Philippines",  // CountryPhilippines
    "Saudi Arabia",  // CountrySaudiArabia
    "UAE",  // CountryUae
    "Qatar",  // CountryQatar
    "Israel",  // CountryIsrael
    "Egypt",  // CountryEgypt
    "Morocco",  // CountryMorocco
    "Algeria",  // CountryAlgeria
    "South Africa",  // CountrySouthAfrica
    "Nigeria",  // CountryNigeria
    "Kenya",  // CountryKenya
    "All Channels",  // NavAllChannels
    "★ Favourites",  // NavFavourites
    "📺 TV Guide",  // NavTvGuide
    "Groups",  // NavGroups
    "Countries",  // NavCountries
    "Playlists",  // NavPlaylists
    "{0} ({1})",  // NavPlaylistNameCount
    // --- Status ---
    "Show buffer fluid",  // BufferMeterShow
    "Hide buffer fluid",  // BufferMeterHide
    "This channel has no tvg-id — the guide can't match it.",  // StatusChannelNoTvgId
    "No guide row for {0} — try Refresh Guide…",  // StatusNoGuideRowForChannel
    "No channels yet — click “+ Add Playlist”.",  // StatusNoChannelsYet
    "Stopped",  // StatusStopped
    "Playlist renamed to \"{0}\"",  // StatusPlaylistRenamed
    "Playlist deleted",  // StatusPlaylistDeleted
    "Opening: {0}",  // StatusOpening
    "Buffering {0}%  —  {1}",  // StatusBuffering
    "Playing: {0}",  // StatusPlaying
    "Paused: {0}",  // StatusPaused
    "Stream ended",  // StatusStreamEnded
    "Unavailable (offline or geo-locked): {0}",  // StatusUnavailable
    "A playlist is still loading — please wait…",  // StatusPlaylistLoadingWait
    "Exported {0} favourites.",  // StatusExportedFavourites
    "Layout limit reached ({0}) — delete one first.",  // StatusLayoutLimitReached
    "Layout saved: {0}",  // StatusLayoutSaved
    "Add playlist failed: could not save to the database",  // StatusAddPlaylistFailedDb
    "Added {0} channels from {1}",  // StatusAddedChannels
    "Add playlist failed: {0}",  // StatusAddPlaylistFailed
    "Busy — please wait…",  // StatusBusyWait
    "Downloading guide…",  // StatusDownloadingGuide
    "Removed from Favourites: {0}",  // StatusRemovedFavourite
    "Added to Favourites: {0}",  // StatusAddedFavourite
    "Guide URL cleared",  // StatusGuideUrlCleared
    "Guide URL saved — run Settings ▸ Refresh Guide to fetch it",  // StatusGuideUrlSaved
    "A scheduled recording owns this pane — manage it in Scheduled Recordings.",  // StatusScheduleOwnsPane
    "Recording saved: {0}",  // StatusRecordingSaved
    "Play a channel first, then Record.",  // StatusPlayChannelFirst
    "● Recording {0}  →  {1}",  // StatusRecordingNow
    "Scheduled recording saved.",  // StatusScheduledRecordingSaved
    "● Recording (scheduled) {0}",  // StatusRecordingScheduledNow
    "Airing cancelled — it came from a series rule, so it stays listed as Cancelled. Delete the rule to stop the series.",  // StatusAiringCancelledRule
    "No categories to filter — this library has no group titles.",  // StatusNoCategories
    "Layout applied: {0}",  // StatusLayoutApplied
    "Layout deleted: {0}",  // StatusLayoutDeleted
    "Wake-to-record off — recordings need the app running.",  // StatusWakeToRecordOff
    "This PC will wake for scheduled recordings.",  // StatusWakeWillWake
    "Wake task started — the scheduled-wake launch path is running now.",  // StatusWakeTaskStarted
    "Could not start the wake task. Check the log; is one queued?",  // StatusWakeTaskFailed
    "{0} channels",  // StatusChannelCount
    "PIP: {0}",  // StatusPipChannel
    "Downloading playlist…",  // StatusDownloadingPlaylist
    "Loading playlist…",  // StatusLoadingPlaylist
    "Active pane {0}",  // StatusActivePane
    "Active: {0}",  // StatusActiveChannel
    // --- Playlist ---
    "Group",  // GridHeaderGroup
    "Channel",  // LabelChannel
    "Rename…",  // MenuPlaylistRename
    "Delete Playlist",  // DeletePlaylistTitle
    "Rename Playlist",  // DialogRenamePlaylistTitle
    "Playlist name:",  // DialogRenamePlaylistLabel
    "Delete playlist \"{0}\"?\\n\\nThis removes its channels from RabbitEars.",  // DialogDeletePlaylistBody
    "Add Playlist",  // AddPlaylistDialogTitle
    "Playlist URL (.m3u / .m3u8):",  // AddPlaylistUrlPrompt
    "Source:  {0}\\r\\n\\r\\n",  // PlaylistSourceLine
    "Could not import the playlist",  // PlaylistImportFailedHeading
    "Problem:  the playlist could not be saved to the database.\\r\\n",  // PlaylistDbSaveProblem
    "Imported {0} channels from {1}",  // PlaylistImportedHeading
    "Channels parsed:  {0}\\r\\n",  // PlaylistChannelsParsedLine
    "Channels imported:  {0}\\r\\n",  // PlaylistChannelsImportedLine
    "Skipped (blank or duplicate URLs):  {0}\\r\\n",  // PlaylistSkippedLine
    "Groups:  {0}\\r\\n",  // PlaylistGroupsLine
    "The playlist contained no channels.",  // PlaylistNoChannelsMsg
    "No channels found.",  // PlaylistNoChannelsFoundMsg
    "Import results",  // ImportResultsTitle
    // --- Transport ---
    "\\r\\nReceived: %.2f Mb/s\\r\\nBuffered: %.1f s",  // TooltipBufferReceivedBuffered
    "Consumption: %.2f Mb/s\\r\\nBuffer (latency): %.1f s\\r\\nRecent loss: %d%s",  // TooltipBufferConsumption
    "Not playing\\r\\nBuffer (latency): %.1f s",  // TooltipBufferNotPlaying
    "Network buffer: %.1f s (receive->show delay)",  // TooltipNetworkBuffer
    "Audio spectrum (this app's sound)",  // TooltipMeterSpectrum
    "Signal strength (stream health)",  // TooltipMeterSignal
    "Stream bitrate history",  // TooltipMeterBitrate
    "Frame rate (flares red on dropped frames)",  // TooltipMeterFrames
    "Pause",  // TooltipBtnPause
    "Stop",  // TooltipBtnStop
    "Stop recording",  // TooltipBtnStopRecording
    "Record",  // TooltipBtnRecord
    "Volume: %d%%",  // TooltipVolume
    "%.1f Mb/s",  // MeterOverlayMbps
    "%.0f kb/s",  // MeterOverlayKbps
    "Buffer %.1f s",  // TransportBufferSeconds
    "+  Add Playlist",  // CmdAddPlaylist
    "Settings",  // TooltipSettings
    // --- GuideGrid ---
    "Programme",  // ProgrammeWindowTitle
    "Play channel",  // ProgrammePlayButton
    "Schedule…",  // ProgrammeScheduleButton
    "{0} – {1}",  // GuideTimeRange
    "Remove from Favourites",  // GuideRemoveFromFavourites
    "★  Add to Favourites",  // GuideAddToFavourites
    "TV Guide — RabbitEars",  // GuideWindowTitle
    "Refresh Guide",  // RefreshGuideTitle
    "No guide source found",  // RefreshGuideNoSourceHeading
    "None of your enabled playlists carry an XMLTV guide URL (x-tvg-url in the #EXTM3U header).\\r\\n\\r\\nAdd a playlist that includes one, then try again.",  // RefreshGuideNoSourceBody
    "TV Guide",  // TvGuideTitle
    "Contacting guide source…",  // LoadingContactingGuide
    " ({0} of {1})",  // LoadingProgressTag
    "Downloading {0}…{1}",  // LoadingDownloadingName
    "Parsing {0} ({1} KB)…{2}",  // LoadingParsingName
    "{0}:  {1} programmes\\r\\n",  // EpgDetailProgrammesLine
    "Stored {0} programmes across {1} channels",  // EpgStoredSummary
    "Could not refresh the guide",  // EpgRefreshFailedSummary
    " · {0} queued by rules",  // EpgQueuedByRulesSummary
    "Building the guide from stored programmes…",  // LoadingBuildingGuide
    "No guide to show",  // GuideNoGuideHeading
    "No stored programmes match a channel in your playlists.\\r\\n\\r\\nEither run Settings ▸ Refresh Guide… first, or the guide's channel IDs don't match your playlist — point it at a guide whose tvg-ids line up (right-click a playlist ▸ Set Guide URL…).",  // GuideNoGuideBody
    "No matching channel",  // GuideNoMatchHeading
    "Couldn't find a channel for \"{0}\" in your playlist.\\r\\n\\r\\nThe guide matches programmes to channels by tvg-id — this programme's channel ID has no match. Point the playlist at a guide whose IDs match it (right-click the playlist ▸ Set Guide URL…).",  // GuideNoMatchBody
    "Set Guide URL",  // SetGuideUrlTitle
    "XMLTV guide URL (.xml or .xml.gz; blank to clear):",  // SetGuideUrlPrompt
    "Guide URL saved.\\n\\nDownload the guide now?",  // SetGuideUrlSavedPrompt
    // --- DialogSchedule ---
    "Channel:",  // ScheduleFieldChannel
    "Title:",  // ScheduleFieldTitle
    "Start:",  // ScheduleFieldStart
    "Stop:",  // ScheduleFieldStop
    "New Recording Schedule",  // ScheduleNewWindowTitle
    "Schedule Recording",  // ScheduleEditWindowTitle
    "Pending",  // ScheduleStatusPending
    "● Recording",  // ScheduleStatusRecording
    "Done",  // ScheduleStatusDone
    "Missed",  // ScheduleStatusMissed
    "Failed",  // ScheduleStatusFailed
    "Cancelled",  // ScheduleStatusCancelled
    "(untitled)",  // ScheduleUntitledPlaceholder
    "Scheduled Recordings",  // ScheduleManagerWindowTitle
    "Title",  // ScheduleColTitle
    "When",  // ScheduleColWhen
    "Status",  // ScheduleColStatus
    "New…",  // ScheduleManagerNewButton
    "Cancel recording",  // ScheduleManagerCancelButton
    "Switching the view stops %d background recording(s) (the file will be finalized). Continue?",  // ViewSwitchStopRecordingConfirm
    "Schedule recording",  // ScheduleRecordingTitle
    "Channel not found",  // ChannelNotFoundHeading
    "Couldn't match \"{0}\" to a playable channel in your library (its tvg-id isn't in an enabled playlist).",  // ScheduleChannelNotFoundBody
    "Recording scheduled",  // ScheduleRecordingScheduledHeading
    "{0}\\r\\n{1}\\r\\n\\r\\nThe app must be running at the scheduled time.",  // ScheduleRecordingScheduledBody
    "Could not schedule",  // ScheduleCouldNotHeading
    "The recording could not be saved.",  // ScheduleCouldNotBody
    // --- DialogRules ---
    "(any)",  // RuleAnyTitlePlaceholder
    "(any channel)",  // RuleAnyChannelPlaceholder
    "Exact title",  // RuleMatchExact
    "Title contains",  // RuleMatchContains
    "Enabled",  // RuleStateEnabled
    "Disabled",  // RuleStateDisabled
    "Delete the rule for \"{0}\"?\r\n\r\nUpcoming recordings it queued will be removed. Recordings that already ran are kept.",  // RuleDeleteConfirm
    "Recording Rules",  // RecordingRulesTitle
    "Show",  // RuleColShow
    "Match",  // RuleColMatch
    "State",  // RuleColState
    "Rules are created from the TV Guide: click a programme, then “Record series”. Every future airing is queued automatically.",  // RulesEmptyHint
    "Enable / Disable",  // RuleToggleButton
    "\\r\\nRecording rules queued {0} new airing(s).\\r\\n",  // EpgRulesQueuedDetail
    "Record series",  // RecordSeriesTitle
    "Couldn't match \"{0}\" to a playable channel in your library.",  // RecordSeriesChannelNotFoundBody
    "Already recording this series",  // RecordSeriesAlreadyHeading
    "A rule for \"{0}\" on {1} already exists.\\r\\nSee Settings ▸ Recording Rules….",  // RecordSeriesAlreadyBody
    "Could not save the rule",  // RecordSeriesCouldNotSaveHeading
    "The recording rule could not be stored.",  // RecordSeriesCouldNotSaveBody
    "Recording every airing of this show",  // RecordSeriesEveryAiringHeading
    "{0}\\r\\n{1}\\r\\n\\r\\n{2} upcoming airing(s) queued from the guide.\\r\\nNew airings are picked up automatically as the guide refreshes.\\r\\n\\r\\nManage rules in Settings ▸ Recording Rules….",  // RecordSeriesEveryAiringBody
    // --- DialogMeters ---
    "Glow",  // MeterKnobGlow
    "Smooth",  // MeterKnobSmooth
    "Sens",  // MeterKnobSens
    "Peak",  // MeterPeak
    "Breathe",  // MeterKnobBreathe
    "12.4 Mb/s",  // MeterPreviewSampleBitrate
    "Meters",  // MetersWindowTitle
    "Enable each meter, pick its look, and set its colours.",  // MetersHeading
    "Audio spectrum",  // MeterNameAudioSpectrum
    "Signal strength",  // MeterNameSignalStrength
    "Bitrate",  // MeterNameBitrate
    "Frame rate",  // MeterNameFrameRate
    "LED",  // MeterLookLed
    "Vacuum tube",  // MeterLookVacuumTube
    "LCD",  // MeterLookLcd
    "Oscilloscope",  // MeterLookOscilloscope
    "Bg",  // MeterRoleBg
    "Dim",  // MeterRoleDim
    "Low",  // MeterRoleLow
    "Mid",  // MeterRoleMid
    "High",  // MeterRoleHigh
    "Accent",  // MeterRoleAccent
    "Data flow",  // MeterDataFlowCheckbox
    "The buffering tank shown at the far right of the transport bar. You can also hide it by right-clicking the meter itself.",  // MeterDataFlowNote
    "Reset to defaults",  // MetersResetButton
    // --- DialogAbout ---
    "github.com/arcanii/RabbitEars",  // AboutGithubLinkLabel
    "ARM64",  // AboutArchArm64
    "x64",  // AboutArchX64
    "x86",  // AboutArchX86
    "unknown",  // AboutArchUnknown
    " (emulated on ARM64)",  // AboutArchEmulatedOnArm64
    " (emulated)",  // AboutArchEmulated
    "A simple IPTV viewer for Windows.\r\nVersion {0}  ·  {1}",  // AboutVersionLine
    "Plays media with libVLC (LGPL-2.1)\r\n© VideoLAN and the VLC contributors.",  // AboutLibVlcCredit
    "Rabbit Ears is provided only for educational purposes, and does not represent supporting any illegal activity that you do with it. We don't know, we don't care.",  // AboutEducationalDisclaimer
    "About RabbitEars",  // AboutWindowTitle
    "Check for Updates…",  // AboutCheckForUpdatesButton
    // --- DialogTerms ---
    "Please read these terms before using RabbitEars. By choosing “I Accept” you agree to them. If you do not agree, choose “Decline” and the application will close.\r\n\r\n1.  Educational purpose.  RabbitEars is a media player provided for educational and personal use only. It is offered “as is”, without warranty of any kind, and you use it entirely at your own risk.\r\n\r\n2.  No content is included.  RabbitEars ships with no channels, playlists, or media of any kind. It plays only the playlists that you choose to add. You are solely responsible for obtaining your playlists from lawful sources and for ensuring that your use complies with all applicable laws and the rights of content owners in your jurisdiction.\r\n\r\n3.  No endorsement.  The authors of RabbitEars do not provide, host, recommend, or endorse any stream or content, and have no knowledge of or control over what you choose to play. As the project puts it: we don’t know, and we don’t care.\r\n\r\n4.  Your responsibility.  Any illegal activity carried out with this software is yours alone and is not supported, encouraged, or condoned by the authors.\r\n\r\n5.  Open source.  RabbitEars plays media using libVLC, © VideoLAN and the VLC contributors, under the GNU LGPL v2.1.\r\n\r\nBy clicking “I Accept”, you confirm that you have read, understood, and agree to these terms.",  // TermsBodyText
    "RabbitEars — Terms of Use",  // TermsWindowTitle
    "Terms of Use",  // TermsHeading
    "I Accept",  // TermsAcceptButton
    "Decline",  // TermsDeclineButton
    // --- Splash ---
    "Loading",  // LoadingWindowTitle
    "Loading TV guide…",  // LoadingHeading
    "Finding the power plug…",  // SplashFindingPowerPlug
    "Connecting wires to the antenna…",  // SplashConnectingWires
    "Bending the left ear to the right…",  // SplashBendingLeftEar
    "Triangulating the wave-motion receptors…",  // SplashTriangulatingReceptors
    "Warming up the vacuum tubes…",  // SplashWarmingVacuumTubes
    "Untangling the coaxial cable…",  // SplashUntanglingCoax
    "Polishing the rabbit ears…",  // SplashPolishingRabbitEars
    "Shooing off the static gremlins…",  // SplashShooingStaticGremlins
    "Finding where Arch keeps his cookies…",  // SplashFindingArchCookies
    "Locking onto the nearest tower…",  // SplashLockingOntoTower
    "Tuning the horizontal hold…",  // SplashTuningHorizontalHold
    "Nudging the aerial a smidge…",  // SplashNudgingAerial
    "Almost picking up a signal…",  // SplashAlmostSignal
    "v{0}",  // SplashVersionLabel
    // --- Error ---
    "Database error: {0}",  // StatusDatabaseError
    "Could not write the file",  // ExportFavouritesWriteFailHeading
    "Path:  {0}\\r\\n",  // ExportFavouritesPathLine
    "Problem:  {0}\\r\\n",  // ProblemLineDetail
    "download failed",  // EpgErrorDownloadFailed
    "empty or invalid after decompression",  // EpgErrorEmptyAfterDecompress
    // --- Misc ---
    "%d of %d categories selected",  // CategoriesSelectedCount
    "Show channels only from the checked categories:",  // CategoriesPrompt
    "OK",  // ButtonOk
    "Filter categories…",  // CategoriesFilterCue
    "Select All",  // CategoriesSelectAllButton
    "Clear",  // CategoriesClearButton
    "Cancel",  // ButtonCancel
    "Close",  // ButtonClose
    "Delete",  // ButtonDelete
    "Search channels…",  // SearchChannelsPlaceholder
    "Picture-in-Picture\\r\\nRight-click a channel ▸ Play in PIP",  // HintEmptyPip
    "Export favourites",  // ExportFavouritesTitle
    "No favourites yet",  // ExportFavouritesNoneHeading
    "Star some channels first (the ★ column in the channel list, or right-click a TV-Guide row), then export.\\r\\n",  // ExportFavouritesNoneBody
    "Exported {0} favourite(s)",  // ExportFavouritesDoneHeading
    "File:  {0}\\r\\n",  // FileLineDetail
    "Import favourites",  // ImportFavouritesTitle
    "No channels found",  // ImportFavouritesNoChannelsHeading
    "File:  {0}\\r\\nEntries in file:  {1}\\r\\nChannels starred:  {2}\\r\\n",  // ImportFavouritesDetails
    "Not in your library (skipped):  {0}\\r\\n",  // ImportFavouritesSkippedLine
    "Starred {0} channel(s)",  // ImportFavouritesStarredHeading
    "My layout",  // LayoutDefaultName
    "Save Layout",  // SaveLayoutDialogTitle
    "Layout name:",  // SaveLayoutNamePrompt
    "RabbitEars",  // AppName
    "Categories",  // CategoriesTitle
    "No categories to filter",  // CategoriesNoneHeading
    "The channels in your library have no group titles, so there are no categories to include or exclude.\\r\\n\\r\\nAdd a playlist whose #EXTINF lines carry group-title tags to use this filter.\\r\\n",  // CategoriesNoneBody
}};

// 日本語
constexpr std::array<const char*, N> kJa = {{
    // --- Menu ---
    "再生",  // LabelPlay
    "PIPで再生",  // MenuChannelPlayInPip
    "番組表に表示",  // MenuChannelShowInGuide
    "全画面表示",  // Fullscreen
    "ビデオのみ",  // MenuVideoOnlyPlain
    "シングル表示",  // MenuSingleView
    "分割表示 (2×2)",  // MenuSplitView
    "MPEG-TS  (.ts)",  // MenuFormatMpegTs
    "Matroska  (.mkv)",  // MenuFormatMatroska
    "MP4  (.mp4)",  // MenuFormatMp4
    "ファイルを開く…",  // MenuOpenFile
    "録画フォーマット",  // MenuRecordingFormat
    "視聴不可のチャンネルを非表示",  // MenuHideUnavailable
    "カテゴリ…",  // MenuCategories
    "お気に入りをエクスポート…",  // MenuExportFavourites
    "お気に入りをインポート…",  // MenuImportFavourites
    "番組表を更新…",  // MenuRefreshGuide
    "録画予約…",  // MenuScheduledRecordings
    "録画ルール…",  // MenuRecordingRules
    "録画のためにこのPCをスリープ解除",  // MenuWakeToRecord
    "復帰タスクを今すぐ実行",  // MenuRunWakeTaskNow
    "メーター…",  // MenuMeters
    "ビデオのみ\\tCtrl+Shift+V",  // MenuVideoOnly
    "前回のチャンネルを再開",  // MenuResumeLastChannel
    "シングル",  // MenuViewSingle
    "分割 (2×2)",  // MenuViewSplit
    "ピクチャー・イン・ピクチャー",  // MenuPictureInPicture
    "表示",  // MenuView
    "デフォルトに戻す",  // MenuLayoutResetDefault
    "サイドバーを移動",  // MenuMoveSidebar
    "ビデオを移動",  // MenuMoveVideo
    "チャンネルを移動",  // MenuMoveChannels
    "左へ",  // MenuDockToLeft
    "右へ",  // MenuDockToRight
    "上へ",  // MenuDockToTop
    "下へ",  // MenuDockToBottom
    "レイアウトに名前を付けて保存…",  // MenuSaveLayoutAs
    "保存したレイアウトを適用",  // MenuApplySavedLayout
    "保存したレイアウトを削除",  // MenuDeleteSavedLayout
    "レイアウト",  // MenuLayout
    "システムに従う",  // MenuThemeFollowSystem
    "テーマ",  // MenuTheme
    "RabbitEars について…",  // MenuAbout
    "言語",  // MenuLanguage
    "システムの既定",  // LangSystemDefault
    "English",  // LangEnglish
    "日本語",  // LangJapanese
    "チャンネル",  // MenuChannels
    "録画",  // MenuRecording
    "表示言語を変更するには再起動してください",  // LangRestartInstruction
    "新しい言語を適用するには RabbitEars を再起動する必要があります。",  // LangRestartBody
    "今すぐ再起動",  // LangRestartNow
    "後で",  // LangRestartLater
    // --- Nav ---
    "番組表URLを設定…",  // MenuSetGuideUrl
    "番組表URLを設定…（プレイリストなし）",  // MenuGuideSetUrlNoPlaylists
    "アメリカ合衆国",  // CountryUnitedStates
    "イギリス",  // CountryUnitedKingdom
    "カナダ",  // CountryCanada
    "オーストラリア",  // CountryAustralia
    "ニュージーランド",  // CountryNewZealand
    "アイルランド",  // CountryIreland
    "ドイツ",  // CountryGermany
    "フランス",  // CountryFrance
    "スペイン",  // CountrySpain
    "イタリア",  // CountryItaly
    "ポルトガル",  // CountryPortugal
    "オランダ",  // CountryNetherlands
    "ベルギー",  // CountryBelgium
    "スイス",  // CountrySwitzerland
    "オーストリア",  // CountryAustria
    "スウェーデン",  // CountrySweden
    "ノルウェー",  // CountryNorway
    "デンマーク",  // CountryDenmark
    "フィンランド",  // CountryFinland
    "ポーランド",  // CountryPoland
    "チェコ",  // CountryCzechia
    "スロバキア",  // CountrySlovakia
    "ハンガリー",  // CountryHungary
    "ルーマニア",  // CountryRomania
    "ブルガリア",  // CountryBulgaria
    "ギリシャ",  // CountryGreece
    "トルコ",  // CountryTurkey
    "ロシア",  // CountryRussia
    "ウクライナ",  // CountryUkraine
    "セルビア",  // CountrySerbia
    "クロアチア",  // CountryCroatia
    "スロベニア",  // CountrySlovenia
    "アルバニア",  // CountryAlbania
    "ブラジル",  // CountryBrazil
    "メキシコ",  // CountryMexico
    "アルゼンチン",  // CountryArgentina
    "チリ",  // CountryChile
    "コロンビア",  // CountryColombia
    "ペルー",  // CountryPeru
    "ベネズエラ",  // CountryVenezuela
    "インド",  // CountryIndia
    "パキスタン",  // CountryPakistan
    "バングラデシュ",  // CountryBangladesh
    "中国",  // CountryChina
    "日本",  // CountryJapan
    "韓国",  // CountrySouthKorea
    "インドネシア",  // CountryIndonesia
    "マレーシア",  // CountryMalaysia
    "シンガポール",  // CountrySingapore
    "タイ",  // CountryThailand
    "ベトナム",  // CountryVietnam
    "フィリピン",  // CountryPhilippines
    "サウジアラビア",  // CountrySaudiArabia
    "アラブ首長国連邦",  // CountryUae
    "カタール",  // CountryQatar
    "イスラエル",  // CountryIsrael
    "エジプト",  // CountryEgypt
    "モロッコ",  // CountryMorocco
    "アルジェリア",  // CountryAlgeria
    "南アフリカ",  // CountrySouthAfrica
    "ナイジェリア",  // CountryNigeria
    "ケニア",  // CountryKenya
    "すべてのチャンネル",  // NavAllChannels
    "★ お気に入り",  // NavFavourites
    "📺 番組表",  // NavTvGuide
    "グループ",  // NavGroups
    "国",  // NavCountries
    "プレイリスト",  // NavPlaylists
    "{0}（{1}）",  // NavPlaylistNameCount
    // --- Status ---
    "バッファ流体を表示",  // BufferMeterShow
    "バッファ流体を非表示",  // BufferMeterHide
    "このチャンネルには tvg-id がありません — 番組表と照合できません。",  // StatusChannelNoTvgId
    "{0} の番組表の行がありません — 番組表を更新… をお試しください",  // StatusNoGuideRowForChannel
    "チャンネルがまだありません — 「+ プレイリストを追加」をクリックしてください。",  // StatusNoChannelsYet
    "停止しました",  // StatusStopped
    "プレイリスト名を「{0}」に変更しました",  // StatusPlaylistRenamed
    "プレイリストを削除しました",  // StatusPlaylistDeleted
    "開いています: {0}",  // StatusOpening
    "バッファ中 {0}%  —  {1}",  // StatusBuffering
    "再生中: {0}",  // StatusPlaying
    "一時停止中: {0}",  // StatusPaused
    "ストリームが終了しました",  // StatusStreamEnded
    "視聴不可（オフラインまたは地域制限）: {0}",  // StatusUnavailable
    "プレイリストを読み込み中です — お待ちください…",  // StatusPlaylistLoadingWait
    "{0} 件のお気に入りをエクスポートしました。",  // StatusExportedFavourites
    "レイアウトの上限に達しました（{0}）— 先に1つ削除してください。",  // StatusLayoutLimitReached
    "レイアウトを保存しました: {0}",  // StatusLayoutSaved
    "プレイリストの追加に失敗しました: データベースに保存できませんでした",  // StatusAddPlaylistFailedDb
    "{1} から {0} チャンネルを追加しました",  // StatusAddedChannels
    "プレイリストの追加に失敗しました: {0}",  // StatusAddPlaylistFailed
    "処理中 — お待ちください…",  // StatusBusyWait
    "番組表をダウンロード中…",  // StatusDownloadingGuide
    "お気に入りから削除しました: {0}",  // StatusRemovedFavourite
    "お気に入りに追加しました: {0}",  // StatusAddedFavourite
    "番組表URLをクリアしました",  // StatusGuideUrlCleared
    "番組表URLを保存しました — 取得するには 設定 ▸ 番組表を更新 を実行してください",  // StatusGuideUrlSaved
    "このペインは録画予約が占有しています — 「録画予約」で管理してください。",  // StatusScheduleOwnsPane
    "録画を保存しました: {0}",  // StatusRecordingSaved
    "先にチャンネルを再生してから録画してください。",  // StatusPlayChannelFirst
    "● {0} を録画中  →  {1}",  // StatusRecordingNow
    "録画予約を保存しました。",  // StatusScheduledRecordingSaved
    "● 録画中（予約）{0}",  // StatusRecordingScheduledNow
    "放送をキャンセルしました — シリーズのルールによるものなので、キャンセル済みとして一覧に残ります。シリーズを停止するにはルールを削除してください。",  // StatusAiringCancelledRule
    "フィルターするカテゴリがありません — このライブラリにはグループタイトルがありません。",  // StatusNoCategories
    "レイアウトを適用しました: {0}",  // StatusLayoutApplied
    "レイアウトを削除しました: {0}",  // StatusLayoutDeleted
    "録画のためのスリープ解除がオフです — 録画にはアプリが起動している必要があります。",  // StatusWakeToRecordOff
    "このPCは録画予約のためにスリープ解除します。",  // StatusWakeWillWake
    "復帰タスクを開始しました — 予約復帰の起動処理が実行中です。",  // StatusWakeTaskStarted
    "復帰タスクを開始できませんでした。ログを確認してください。予約はありますか？",  // StatusWakeTaskFailed
    "{0} チャンネル",  // StatusChannelCount
    "PIP: {0}",  // StatusPipChannel
    "プレイリストをダウンロード中…",  // StatusDownloadingPlaylist
    "プレイリストを読み込み中…",  // StatusLoadingPlaylist
    "アクティブなペイン {0}",  // StatusActivePane
    "アクティブ: {0}",  // StatusActiveChannel
    // --- Playlist ---
    "グループ",  // GridHeaderGroup
    "チャンネル",  // LabelChannel
    "名前を変更…",  // MenuPlaylistRename
    "プレイリストを削除",  // DeletePlaylistTitle
    "プレイリストの名前を変更",  // DialogRenamePlaylistTitle
    "プレイリスト名:",  // DialogRenamePlaylistLabel
    "プレイリスト「{0}」を削除しますか?\\n\\nこのプレイリストのチャンネルが RabbitEars から削除されます。",  // DialogDeletePlaylistBody
    "プレイリストを追加",  // AddPlaylistDialogTitle
    "プレイリスト URL (.m3u / .m3u8):",  // AddPlaylistUrlPrompt
    "ソース:  {0}\\r\\n\\r\\n",  // PlaylistSourceLine
    "プレイリストをインポートできませんでした",  // PlaylistImportFailedHeading
    "問題:  プレイリストをデータベースに保存できませんでした。\\r\\n",  // PlaylistDbSaveProblem
    "{1} から {0} 件のチャンネルをインポートしました",  // PlaylistImportedHeading
    "解析したチャンネル:  {0}\\r\\n",  // PlaylistChannelsParsedLine
    "インポートしたチャンネル:  {0}\\r\\n",  // PlaylistChannelsImportedLine
    "スキップ (空または重複する URL):  {0}\\r\\n",  // PlaylistSkippedLine
    "グループ:  {0}\\r\\n",  // PlaylistGroupsLine
    "プレイリストにチャンネルがありませんでした。",  // PlaylistNoChannelsMsg
    "チャンネルが見つかりませんでした。",  // PlaylistNoChannelsFoundMsg
    "インポート結果",  // ImportResultsTitle
    // --- Transport ---
    "\\r\\n受信: %.2f Mb/s\\r\\nバッファ済み: %.1f 秒",  // TooltipBufferReceivedBuffered
    "消費: %.2f Mb/s\\r\\nバッファ (遅延): %.1f 秒\\r\\n直近の損失: %d%s",  // TooltipBufferConsumption
    "再生していません\\r\\nバッファ (遅延): %.1f 秒",  // TooltipBufferNotPlaying
    "ネットワークバッファ: %.1f 秒 (受信→表示の遅延)",  // TooltipNetworkBuffer
    "オーディオスペクトラム (このアプリの音声)",  // TooltipMeterSpectrum
    "信号強度 (ストリームの状態)",  // TooltipMeterSignal
    "ストリームのビットレート履歴",  // TooltipMeterBitrate
    "フレームレート (フレーム落ち時に赤く点灯)",  // TooltipMeterFrames
    "一時停止",  // TooltipBtnPause
    "停止",  // TooltipBtnStop
    "録画を停止",  // TooltipBtnStopRecording
    "録画",  // TooltipBtnRecord
    "音量: %d%%",  // TooltipVolume
    "%.1f Mb/s",  // MeterOverlayMbps
    "%.0f kb/s",  // MeterOverlayKbps
    "バッファ %.1f 秒",  // TransportBufferSeconds
    "＋  プレイリストを追加",  // CmdAddPlaylist
    "設定",  // TooltipSettings
    // --- GuideGrid ---
    "番組",  // ProgrammeWindowTitle
    "チャンネルを再生",  // ProgrammePlayButton
    "予約…",  // ProgrammeScheduleButton
    "{0} – {1}",  // GuideTimeRange
    "お気に入りから削除",  // GuideRemoveFromFavourites
    "★  お気に入りに追加",  // GuideAddToFavourites
    "番組表 — RabbitEars",  // GuideWindowTitle
    "番組表を更新",  // RefreshGuideTitle
    "番組表のソースが見つかりません",  // RefreshGuideNoSourceHeading
    "有効なプレイリストのいずれにもXMLTV番組表URL（#EXTM3Uヘッダー内のx-tvg-url）が含まれていません。\\r\\n\\r\\n番組表URLを含むプレイリストを追加してから、もう一度お試しください。",  // RefreshGuideNoSourceBody
    "番組表",  // TvGuideTitle
    "番組表のソースに接続中…",  // LoadingContactingGuide
    " （{1} 件中 {0} 件）",  // LoadingProgressTag
    "{0} をダウンロード中…{1}",  // LoadingDownloadingName
    "{0} を解析中 ({1} KB)…{2}",  // LoadingParsingName
    "{0}:  {1} 番組\\r\\n",  // EpgDetailProgrammesLine
    "{1} チャンネルにわたって {0} 番組を保存しました",  // EpgStoredSummary
    "番組表を更新できませんでした",  // EpgRefreshFailedSummary
    " · ルールにより {0} 件をキューに追加",  // EpgQueuedByRulesSummary
    "保存された番組から番組表を構築中…",  // LoadingBuildingGuide
    "表示する番組表がありません",  // GuideNoGuideHeading
    "保存された番組の中に、プレイリストのチャンネルと一致するものがありません。\\r\\n\\r\\nまず「設定 ▸ 番組表を更新…」を実行してください。または、番組表のチャンネルIDがプレイリストと一致していない可能性があります。tvg-idが一致する番組表を指定してください（プレイリストを右クリック ▸ 番組表URLを設定…）。",  // GuideNoGuideBody
    "一致するチャンネルがありません",  // GuideNoMatchHeading
    "プレイリスト内に「{0}」に該当するチャンネルが見つかりませんでした。\\r\\n\\r\\n番組表はtvg-idで番組をチャンネルに対応付けます。この番組のチャンネルIDには一致するものがありません。IDが一致する番組表をプレイリストに指定してください（プレイリストを右クリック ▸ 番組表URLを設定…）。",  // GuideNoMatchBody
    "番組表URLを設定",  // SetGuideUrlTitle
    "XMLTV番組表URL (.xml または .xml.gz、空欄でクリア):",  // SetGuideUrlPrompt
    "番組表URLを保存しました。\\n\\n今すぐ番組表をダウンロードしますか？",  // SetGuideUrlSavedPrompt
    // --- DialogSchedule ---
    "チャンネル:",  // ScheduleFieldChannel
    "タイトル:",  // ScheduleFieldTitle
    "開始:",  // ScheduleFieldStart
    "終了:",  // ScheduleFieldStop
    "新規録画予約",  // ScheduleNewWindowTitle
    "録画予約",  // ScheduleEditWindowTitle
    "保留中",  // ScheduleStatusPending
    "● 録画中",  // ScheduleStatusRecording
    "完了",  // ScheduleStatusDone
    "録画漏れ",  // ScheduleStatusMissed
    "失敗",  // ScheduleStatusFailed
    "キャンセル済み",  // ScheduleStatusCancelled
    "（無題）",  // ScheduleUntitledPlaceholder
    "録画予約",  // ScheduleManagerWindowTitle
    "タイトル",  // ScheduleColTitle
    "日時",  // ScheduleColWhen
    "ステータス",  // ScheduleColStatus
    "新規…",  // ScheduleManagerNewButton
    "録画をキャンセル",  // ScheduleManagerCancelButton
    "表示を切り替えると、%d 件のバックグラウンド録画が停止します（ファイルは確定されます）。続行しますか？",  // ViewSwitchStopRecordingConfirm
    "録画予約",  // ScheduleRecordingTitle
    "チャンネルが見つかりません",  // ChannelNotFoundHeading
    "「{0}」をライブラリ内の再生可能なチャンネルに一致させられませんでした（その tvg-id が有効なプレイリストに含まれていません）。",  // ScheduleChannelNotFoundBody
    "録画を予約しました",  // ScheduleRecordingScheduledHeading
    "{0}\\r\\n{1}\\r\\n\\r\\n予約した時刻にアプリが起動している必要があります。",  // ScheduleRecordingScheduledBody
    "予約できませんでした",  // ScheduleCouldNotHeading
    "録画を保存できませんでした。",  // ScheduleCouldNotBody
    // --- DialogRules ---
    "（すべて）",  // RuleAnyTitlePlaceholder
    "（すべてのチャンネル）",  // RuleAnyChannelPlaceholder
    "タイトル完全一致",  // RuleMatchExact
    "タイトル部分一致",  // RuleMatchContains
    "有効",  // RuleStateEnabled
    "無効",  // RuleStateDisabled
    "「{0}」の録画ルールを削除しますか？\r\n\r\nこのルールが予約した今後の録画は削除されます。すでに実行された録画は保持されます。",  // RuleDeleteConfirm
    "録画ルール",  // RecordingRulesTitle
    "番組",  // RuleColShow
    "一致",  // RuleColMatch
    "状態",  // RuleColState
    "ルールは番組表から作成します。番組をクリックして「シリーズ録画」を選択すると、今後のすべての放送が自動的に予約されます。",  // RulesEmptyHint
    "有効 / 無効",  // RuleToggleButton
    "\\r\\n録画ルールが{0}件の新しい放送を予約しました。\\r\\n",  // EpgRulesQueuedDetail
    "シリーズ録画",  // RecordSeriesTitle
    "「{0}」をライブラリ内の再生可能なチャンネルに一致させられませんでした。",  // RecordSeriesChannelNotFoundBody
    "このシリーズはすでに録画中です",  // RecordSeriesAlreadyHeading
    "{1}での「{0}」の録画ルールはすでに存在します。\\r\\n設定 ▸ 録画ルール… を参照してください。",  // RecordSeriesAlreadyBody
    "ルールを保存できませんでした",  // RecordSeriesCouldNotSaveHeading
    "録画ルールを保存できませんでした。",  // RecordSeriesCouldNotSaveBody
    "この番組のすべての放送を録画します",  // RecordSeriesEveryAiringHeading
    "{0}\\r\\n{1}\\r\\n\\r\\n番組表から今後の放送を{2}件予約しました。\\r\\n番組表の更新に合わせて、新しい放送が自動的に取り込まれます。\\r\\n\\r\\nルールの管理は設定 ▸ 録画ルール… で行えます。",  // RecordSeriesEveryAiringBody
    // --- DialogMeters ---
    "グロー",  // MeterKnobGlow
    "スムーズ",  // MeterKnobSmooth
    "感度",  // MeterKnobSens
    "ピーク",  // MeterPeak
    "呼吸",  // MeterKnobBreathe
    "12.4 Mb/s",  // MeterPreviewSampleBitrate
    "メーター",  // MetersWindowTitle
    "各メーターを有効にし、外観を選び、色を設定します。",  // MetersHeading
    "オーディオスペクトラム",  // MeterNameAudioSpectrum
    "信号強度",  // MeterNameSignalStrength
    "ビットレート",  // MeterNameBitrate
    "フレームレート",  // MeterNameFrameRate
    "LED",  // MeterLookLed
    "真空管",  // MeterLookVacuumTube
    "LCD",  // MeterLookLcd
    "オシロスコープ",  // MeterLookOscilloscope
    "背景",  // MeterRoleBg
    "減光",  // MeterRoleDim
    "低",  // MeterRoleLow
    "中",  // MeterRoleMid
    "高",  // MeterRoleHigh
    "アクセント",  // MeterRoleAccent
    "データフロー",  // MeterDataFlowCheckbox
    "トランスポートバーの右端に表示されるバッファリングタンクです。メーター自体を右クリックして非表示にすることもできます。",  // MeterDataFlowNote
    "既定値にリセット",  // MetersResetButton
    // --- DialogAbout ---
    "github.com/arcanii/RabbitEars",  // AboutGithubLinkLabel
    "ARM64",  // AboutArchArm64
    "x64",  // AboutArchX64
    "x86",  // AboutArchX86
    "不明",  // AboutArchUnknown
    "（ARM64上でエミュレート）",  // AboutArchEmulatedOnArm64
    "（エミュレート）",  // AboutArchEmulated
    "Windows向けのシンプルなIPTVビューアー。\r\nバージョン {0}  ·  {1}",  // AboutVersionLine
    "libVLC (LGPL-2.1) でメディアを再生\r\n© VideoLAN および VLC 貢献者。",  // AboutLibVlcCredit
    "RabbitEars は教育目的のみで提供されており、これを使って行ういかなる違法行為も支援するものではありません。私たちは知りませんし、気にもしません。",  // AboutEducationalDisclaimer
    "RabbitEars について",  // AboutWindowTitle
    "更新を確認…",  // AboutCheckForUpdatesButton
    // --- DialogTerms ---
    "RabbitEars をご利用になる前に、本規約をお読みください。「同意する」を選択すると、本規約に同意したものとみなされます。同意されない場合は「同意しない」を選択してください。アプリケーションは終了します。\r\n\r\n1.  教育目的。  RabbitEars は、教育および個人利用のみを目的として提供されるメディアプレーヤーです。いかなる種類の保証もなく「現状のまま」提供され、その利用はすべてお客様ご自身の責任において行われます。\r\n\r\n2.  コンテンツは含まれません。  RabbitEars には、チャンネル、プレイリスト、その他いかなる種類のメディアも同梱されていません。お客様が追加を選択したプレイリストのみを再生します。プレイリストを適法な提供元から入手すること、および、その利用がお客様の管轄地域において適用されるすべての法律とコンテンツ所有者の権利を遵守していることを確保することについては、お客様が単独で責任を負うものとします。\r\n\r\n3.  推奨はしません。  RabbitEars の作者は、いかなるストリームまたはコンテンツも提供、ホスト、推薦、または推奨するものではなく、お客様が再生を選択する内容について何ら把握しておらず、管理もしていません。本プロジェクトの言葉を借りれば、私たちは知りませんし、気にもしません。\r\n\r\n4.  お客様の責任。  本ソフトウェアを用いて行われるいかなる違法行為も、お客様のみの責任であり、作者によって支持、奨励、または容認されるものではありません。\r\n\r\n5.  オープンソース。  RabbitEars は、GNU LGPL v2.1 のもとで、libVLC(© VideoLAN および VLC の貢献者)を使用してメディアを再生します。\r\n\r\n「同意する」をクリックすることにより、お客様は本規約を読み、理解し、これに同意したことを確認するものとします。",  // TermsBodyText
    "RabbitEars — 利用規約",  // TermsWindowTitle
    "利用規約",  // TermsHeading
    "同意する",  // TermsAcceptButton
    "同意しない",  // TermsDeclineButton
    // --- Splash ---
    "読み込み中",  // LoadingWindowTitle
    "番組表を読み込み中…",  // LoadingHeading
    "電源プラグを探しています…",  // SplashFindingPowerPlug
    "アンテナに配線をつないでいます…",  // SplashConnectingWires
    "左の耳を右に曲げています…",  // SplashBendingLeftEar
    "電波受信素子を三点測量しています…",  // SplashTriangulatingReceptors
    "真空管を温めています…",  // SplashWarmingVacuumTubes
    "同軸ケーブルをほどいています…",  // SplashUntanglingCoax
    "ウサギの耳を磨いています…",  // SplashPolishingRabbitEars
    "砂嵐グレムリンを追い払っています…",  // SplashShooingStaticGremlins
    "アーチのクッキーの隠し場所を探しています…",  // SplashFindingArchCookies
    "最寄りの電波塔に照準を合わせています…",  // SplashLockingOntoTower
    "水平同期を調整しています…",  // SplashTuningHorizontalHold
    "アンテナをちょっとだけ動かしています…",  // SplashNudgingAerial
    "もうすぐ電波をキャッチできそうです…",  // SplashAlmostSignal
    "v{0}",  // SplashVersionLabel
    // --- Error ---
    "データベースエラー: {0}",  // StatusDatabaseError
    "ファイルを書き込めませんでした",  // ExportFavouritesWriteFailHeading
    "パス:  {0}\\r\\n",  // ExportFavouritesPathLine
    "問題:  {0}\\r\\n",  // ProblemLineDetail
    "ダウンロードに失敗しました",  // EpgErrorDownloadFailed
    "展開後に空または無効です",  // EpgErrorEmptyAfterDecompress
    // --- Misc ---
    "%d / %d カテゴリを選択",  // CategoriesSelectedCount
    "チェックしたカテゴリのチャンネルのみを表示:",  // CategoriesPrompt
    "OK",  // ButtonOk
    "カテゴリをフィルター…",  // CategoriesFilterCue
    "すべて選択",  // CategoriesSelectAllButton
    "クリア",  // CategoriesClearButton
    "キャンセル",  // ButtonCancel
    "閉じる",  // ButtonClose
    "削除",  // ButtonDelete
    "チャンネルを検索…",  // SearchChannelsPlaceholder
    "ピクチャー・イン・ピクチャー\\r\\nチャンネルを右クリック ▸ PIPで再生",  // HintEmptyPip
    "お気に入りをエクスポート",  // ExportFavouritesTitle
    "お気に入りがまだありません",  // ExportFavouritesNoneHeading
    "先にチャンネルにスターを付けてください(チャンネル一覧の ★ 列、または番組表の行を右クリック)。それからエクスポートしてください。\\r\\n",  // ExportFavouritesNoneBody
    "{0} 件のお気に入りをエクスポートしました",  // ExportFavouritesDoneHeading
    "ファイル:  {0}\\r\\n",  // FileLineDetail
    "お気に入りをインポート",  // ImportFavouritesTitle
    "チャンネルが見つかりません",  // ImportFavouritesNoChannelsHeading
    "ファイル:  {0}\\r\\nファイル内のエントリ:  {1}\\r\\nスターを付けたチャンネル:  {2}\\r\\n",  // ImportFavouritesDetails
    "ライブラリにありません(スキップ):  {0}\\r\\n",  // ImportFavouritesSkippedLine
    "{0} 件のチャンネルにスターを付けました",  // ImportFavouritesStarredHeading
    "マイレイアウト",  // LayoutDefaultName
    "レイアウトを保存",  // SaveLayoutDialogTitle
    "レイアウト名:",  // SaveLayoutNamePrompt
    "RabbitEars",  // AppName
    "カテゴリ",  // CategoriesTitle
    "フィルターするカテゴリがありません",  // CategoriesNoneHeading
    "ライブラリのチャンネルにグループタイトルがないため、含めたり除外したりするカテゴリがありません。\\r\\n\\r\\nこのフィルターを使うには、#EXTINF 行に group-title タグを持つプレイリストを追加してください。\\r\\n",  // CategoriesNoneBody
}};

// One row per Lang value, in enum order — trU8 indexes this by static_cast<size_t>(lang).
constexpr const std::array<const char*, N>* kTables[] = { &kEn, &kJa };
constexpr std::size_t kLangCount = sizeof(kTables) / sizeof(kTables[0]);

// Atomic: the splash worker thread reads the active language (via trU8) to localize its captions
// while the UI thread sets it during startup. Relaxed is enough — no ordering dependency, we only
// need race-free reads/writes of this one enum.
std::atomic<Lang> g_lang{Lang::En};

}  // namespace

Lang activeLang() { return g_lang.load(std::memory_order_relaxed); }
void setActiveLang(Lang l) { g_lang.store(l, std::memory_order_relaxed); }

const char* trU8(StringId id, Lang lang) {
    const std::size_t i = static_cast<std::size_t>(id);
    const std::size_t l = static_cast<std::size_t>(lang);
    if (i >= N || l >= kLangCount) return "";
    const char* s = (*kTables[l])[i];
    return s ? s : "";
}
const char* trU8(StringId id) { return trU8(id, g_lang.load(std::memory_order_relaxed)); }

bool catalogIsComplete(StringId* firstMissing) {
    for (std::size_t i = 0; i < N; ++i)
        for (std::size_t l = 0; l < kLangCount; ++l)
            if (!(*kTables[l])[i] || !(*kTables[l])[i][0]) {
                if (firstMissing) *firstMissing = static_cast<StringId>(i);
                return false;
            }
    return true;
}

int placeholderCount(StringId id, Lang lang) {
    const char* s = trU8(id, lang);
    int n = 0;
    for (const char* p = s; *p; ++p) {
        if (*p == '{' && p[1] >= '0' && p[1] <= '9') ++n;            // {0}, {1}, ...
        else if (*p == '%' && (p[1] == 'd' || p[1] == 's')) ++n;    // %d / %s (%% is skipped)
    }
    return n;
}

}  // namespace i18n
}  // namespace rabbitears
