# SPDX-License-Identifier: GPL-3.0-or-later
r'''Generate common/core/FtsFoldTable.h — the per-character fold SQLite's FTS5 tokenizers apply.

The TV Guide's programme search matches through two FTS5 indexes (common/db/Database.cpp): titles with
`trigram remove_diacritics 1`, descriptions with `unicode61 remove_diacritics 2`. Both fold a character
the same way — case, and the accents they remove — one character to one (or to nothing: a combining
accent the tokenizers drop). Marking what a search found has to fold exactly as they do
(common/core/SearchFold.h ftsFold), so this asks SQLite itself, character by character, and writes the
answer as a table: every BMP character from U+0080 that does not fold to itself.

    python tools/fold/gen_fts_fold.py           write the header
    python tools/fold/gen_fts_fold.py --check   fail if the committed header differs (EOL-agnostic)

It runs Python's own sqlite3 (FTS5 compiled in; trigram's remove_diacritics needs SQLite 3.45+). It
also checks plane 1 (U+10000-U+1FFFF, where every cased script beyond the BMP is): SearchFold.h codes
FTS5's one fold there (Deseret, +40) by hand, so any other stops the generator. RabbitEarsCli
--selftest checks the committed table and that rule against the VENDORED SQLite for every BMP and
plane-1 character, so a SQLite whose fold differs from the one that generated it is caught there.
'''
import os
import sqlite3
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
OUT = os.path.join(ROOT, 'common', 'core', 'FtsFoldTable.h')


def fold_table():
    db = sqlite3.connect(':memory:')
    try:
        db.execute("CREATE VIRTUAL TABLE t USING fts5(x, tokenize='trigram remove_diacritics 1')")
    except sqlite3.Error as e:
        sys.exit(f"gen_fts_fold: this Python's SQLite {sqlite3.sqlite_version} cannot make the index ({e}) - "
                 "it needs FTS5 and trigram remove_diacritics (SQLite 3.45+)")
    db.execute("CREATE VIRTUAL TABLE ti USING fts5vocab(t, 'instance')")
    db.execute("CREATE VIRTUAL TABLE u USING fts5(x, tokenize='unicode61 remove_diacritics 2')")
    db.execute("CREATE VIRTUAL TABLE ui USING fts5vocab(u, 'instance')")
    cps = [c for c in range(0x80, 0x10000) if not 0xD800 <= c <= 0xDFFF]
    with db:
        for c in cps:
            # Trigram keeps every character (a space too) but the accents it drops, so "ccc" is ONE
            # trigram, fold(c) x 3 - or none.
            db.execute('INSERT INTO t(rowid, x) VALUES (?, ?)', (c, chr(c) * 3))
            db.execute('INSERT INTO u(rowid, x) VALUES (?, ?)', (c, chr(c)))
    tri = {doc: term for term, doc in db.execute('SELECT term, doc FROM ti')}
    uni = {doc: term for term, doc in db.execute('SELECT term, doc FROM ui')}
    table = []
    for c in cps:
        t = tri.get(c)
        if t is None:
            f = 0  # dropped: "ccc" left nothing to index
        else:
            if len(t) != 3 or t[0] != t[1] or t[1] != t[2]:
                sys.exit(f'U+{c:04X}: trigram gave {t!r} - not a one-to-one fold')
            f = ord(t[0])
        # unicode61 keeps only token characters; where it keeps one, it must fold it the same way.
        u = uni.get(c)
        if u is not None and (len(u) != 1 or ord(u) != f):
            sys.exit(f'U+{c:04X}: unicode61 folds to {u!r}, trigram to {f:#x} - the indexes disagree')
        if f != c:
            table.append((c, f))
    # Plane 1: SearchFold.h's hand-coded rule (Deseret U+10400-U+10427, +40) must be the whole story.
    db.execute('CREATE VIRTUAL TABLE t1 USING fts5(x, tokenize=\'trigram remove_diacritics 1\')')
    db.execute("CREATE VIRTUAL TABLE t1i USING fts5vocab(t1, 'instance')")
    with db:
        for c in range(0x10000, 0x20000):
            db.execute('INSERT INTO t1(rowid, x) VALUES (?, ?)', (c, chr(c) * 3))
    for term, doc in db.execute('SELECT term, doc FROM t1i'):
        want = doc + 40 if 0x10400 <= doc <= 0x10427 else doc
        if len(term) != 3 or ord(term[0]) != want:
            sys.exit(f'U+{doc:04X}: FTS5 folds it to {term!r} - SearchFold.h ftsFoldCodePoint must learn it')
    return table


def render(table):
    lines = [
        '// SPDX-License-Identifier: GPL-3.0-or-later',
        '// GENERATED by tools/fold/gen_fts_fold.py - do not edit; re-run it (--check compares).',
        '//',
        "// SQLite FTS5's per-character fold for U+0080-U+FFFF, as its tokenizers apply it (trigram",
        '// remove_diacritics 1 and unicode61 remove_diacritics 2 agree): kFrom[i] folds to kTo[i], 0 = the',
        '// tokenizers drop it; a character not listed folds to itself. kFrom is sorted. Used through',
        '// common/core/SearchFold.h; RabbitEarsCli --selftest checks it against the vendored SQLite.',
        '#pragma once',
        '',
        '#include <cstddef>',
        '#include <cstdint>',
        '',
        'namespace rabbitears::fts_fold {',
        '',
        f'inline constexpr std::size_t kCount = {len(table)};',
        '',
    ]
    for name, col in (('kFrom', 0), ('kTo', 1)):
        lines.append(f'inline constexpr std::uint16_t {name}[kCount] = {{')
        vals = [f'0x{row[col]:04X}' for row in table]
        for i in range(0, len(vals), 12):
            lines.append('    ' + ', '.join(vals[i:i + 12]) + ',')
        lines.append('};')
        lines.append('')
    lines.append('}  // namespace rabbitears::fts_fold')
    return '\n'.join(lines) + '\n'


def main():
    table = fold_table()
    text = render(table)
    if '--check' in sys.argv:
        cur = open(OUT, encoding='utf-8', newline='').read() if os.path.exists(OUT) else ''
        if cur.replace('\r\n', '\n') != text:
            sys.exit(f'gen_fts_fold: {OUT} is out of date - run python tools/fold/gen_fts_fold.py')
        print(f'gen_fts_fold: OK ({len(table)} characters, SQLite {sqlite3.sqlite_version})')
        return
    open(OUT, 'w', encoding='utf-8', newline='\n').write(text)
    print(f'gen_fts_fold: wrote {OUT} - {len(table)} characters (SQLite {sqlite3.sqlite_version})')


if __name__ == '__main__':
    main()
